### ISSUE TITLE
KeyError: 'CST'

### ISSUE THREAD

**Issue by loziobrown** [tg12/FAIG#32]
Hi,
i've a problem in execution of the script.

python faig.py
Traceback (most recent call last):
  File "faig.py", line 9, in <module>
    api = API()
  File "/mnt/c/Users/brunettig/Git/FAIG/ig.py", line 27, in __init__
    d = super().session()
  File "/mnt/c/Users/brunettig/Git/FAIG/igclient.py", line 26, in wrap
    return f(*args, **kwargs)
  File "/mnt/c/Users/brunettig/Git/FAIG/igclient.py", line 73, in session
    self.auth[h] = headers_json[h]
KeyError: 'CST'

**Comment by tg12** [comment]
This is the most common error. It is a problem with your IG Index API key. Most common you are using a DEMO account key with a LIVE account or visa versa. For further reading please view. 

https://labs.ig.com/

https://www.ig.com/uk/trading-platforms/trading-apis/how-to-use-ig-api#rest

https://labs.ig.com/faq
